/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TokenManagerInterface extends Interface {
  getFunction(
    nameOrSignature: "purchaseToken" | "purchaseTokenAMAP" | "saleToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "TokenCreate"
      | "TokenPurchase"
      | "TokenSale"
      | "TradeStop"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "purchaseToken",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseTokenAMAP",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "saleToken",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "purchaseToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseTokenAMAP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "saleToken", data: BytesLike): Result;
}

export namespace TokenCreateEvent {
  export type InputTuple = [
    creator: AddressLike,
    token: AddressLike,
    requestId: BigNumberish,
    name: string,
    symbol: string,
    totalSupply: BigNumberish,
    launchTime: BigNumberish,
    launchFee: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    token: string,
    requestId: bigint,
    name: string,
    symbol: string,
    totalSupply: bigint,
    launchTime: bigint,
    launchFee: bigint
  ];
  export interface OutputObject {
    creator: string;
    token: string;
    requestId: bigint;
    name: string;
    symbol: string;
    totalSupply: bigint;
    launchTime: bigint;
    launchFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenPurchaseEvent {
  export type InputTuple = [
    token: AddressLike,
    account: AddressLike,
    tokenAmount: BigNumberish,
    etherAmount: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    account: string,
    tokenAmount: bigint,
    etherAmount: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    token: string;
    account: string;
    tokenAmount: bigint;
    etherAmount: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenSaleEvent {
  export type InputTuple = [
    token: AddressLike,
    account: AddressLike,
    tokenAmount: BigNumberish,
    etherAmount: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    account: string,
    tokenAmount: bigint,
    etherAmount: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    token: string;
    account: string;
    tokenAmount: bigint;
    etherAmount: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeStopEvent {
  export type InputTuple = [token: AddressLike];
  export type OutputTuple = [token: string];
  export interface OutputObject {
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TokenManager extends BaseContract {
  connect(runner?: ContractRunner | null): TokenManager;
  waitForDeployment(): Promise<this>;

  interface: TokenManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  purchaseToken: TypedContractMethod<
    [tokenAddress: AddressLike, amount: BigNumberish, maxFunds: BigNumberish],
    [void],
    "payable"
  >;

  purchaseTokenAMAP: TypedContractMethod<
    [tokenAddress: AddressLike, funds: BigNumberish, minAmount: BigNumberish],
    [void],
    "payable"
  >;

  saleToken: TypedContractMethod<
    [tokenAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "purchaseToken"
  ): TypedContractMethod<
    [tokenAddress: AddressLike, amount: BigNumberish, maxFunds: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "purchaseTokenAMAP"
  ): TypedContractMethod<
    [tokenAddress: AddressLike, funds: BigNumberish, minAmount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "saleToken"
  ): TypedContractMethod<
    [tokenAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "TokenCreate"
  ): TypedContractEvent<
    TokenCreateEvent.InputTuple,
    TokenCreateEvent.OutputTuple,
    TokenCreateEvent.OutputObject
  >;
  getEvent(
    key: "TokenPurchase"
  ): TypedContractEvent<
    TokenPurchaseEvent.InputTuple,
    TokenPurchaseEvent.OutputTuple,
    TokenPurchaseEvent.OutputObject
  >;
  getEvent(
    key: "TokenSale"
  ): TypedContractEvent<
    TokenSaleEvent.InputTuple,
    TokenSaleEvent.OutputTuple,
    TokenSaleEvent.OutputObject
  >;
  getEvent(
    key: "TradeStop"
  ): TypedContractEvent<
    TradeStopEvent.InputTuple,
    TradeStopEvent.OutputTuple,
    TradeStopEvent.OutputObject
  >;

  filters: {
    "TokenCreate(address,address,uint256,string,string,uint256,uint256,uint256)": TypedContractEvent<
      TokenCreateEvent.InputTuple,
      TokenCreateEvent.OutputTuple,
      TokenCreateEvent.OutputObject
    >;
    TokenCreate: TypedContractEvent<
      TokenCreateEvent.InputTuple,
      TokenCreateEvent.OutputTuple,
      TokenCreateEvent.OutputObject
    >;

    "TokenPurchase(address,address,uint256,uint256,uint256)": TypedContractEvent<
      TokenPurchaseEvent.InputTuple,
      TokenPurchaseEvent.OutputTuple,
      TokenPurchaseEvent.OutputObject
    >;
    TokenPurchase: TypedContractEvent<
      TokenPurchaseEvent.InputTuple,
      TokenPurchaseEvent.OutputTuple,
      TokenPurchaseEvent.OutputObject
    >;

    "TokenSale(address,address,uint256,uint256,uint256)": TypedContractEvent<
      TokenSaleEvent.InputTuple,
      TokenSaleEvent.OutputTuple,
      TokenSaleEvent.OutputObject
    >;
    TokenSale: TypedContractEvent<
      TokenSaleEvent.InputTuple,
      TokenSaleEvent.OutputTuple,
      TokenSaleEvent.OutputObject
    >;

    "TradeStop(address)": TypedContractEvent<
      TradeStopEvent.InputTuple,
      TradeStopEvent.OutputTuple,
      TradeStopEvent.OutputObject
    >;
    TradeStop: TypedContractEvent<
      TradeStopEvent.InputTuple,
      TradeStopEvent.OutputTuple,
      TradeStopEvent.OutputObject
    >;
  };
}
